from __future__ import annotations

import json
import logging
import os
import re
from pathlib import Path
from typing import Any

from web3 import Web3
from web3.contract.contract import ContractFunction

from config import Settings

logger = logging.getLogger("vouch.keeper.chain")

_ZERO_ADDRESS = "0x0000000000000000000000000000000000000000"

# Oracle-health custom errors raised by VouchVault._getPrice / getHealthFactor. On testnets
# (Sepolia especially) Chainlink feeds update infrequently, so these reverts are expected and
# transient — not keeper faults. Callers log them quietly instead of as error-level tracebacks.
# Listed by signature; _match_tokens derives the selector so we recognize them even when web3
# can't decode the ABI and only reports the raw selector (e.g. "0x19abf40e").
_TRANSIENT_ORACLE_SIGS = (
    "NoPriceFeed()",
    "InvalidPrice()",
    "RoundNotComplete()",
    "StaleRound()",
    "PriceTimestampInFuture()",
    "StalePrice()",
)

# Errors that mean the loan is no longer liquidatable because the borrower already settled it.
# These are a normal race condition (borrower repays between the HF check and the liquidation tx)
# and should be handled quietly rather than logged as keeper faults.
_ALREADY_SETTLED_SIGS = (
    "LoanAlreadyRepaid()",
    "LoanAlreadyLiquidated()",
)


def _match_tokens(sig: str) -> tuple[str, list[str]]:
    """Build (error_name, lowercased match tokens) for a custom-error signature.

    Web3 can surface the same revert in three forms depending on ABI availability: the raw 4-byte
    selector ("0x19abf40e"), the decoded signature ("StalePrice()"), or a human-readable reason
    ("No price feed for token"). We match all three so an expected oracle revert is recognized
    however it arrives.
    """
    name = sig[:-2]  # strip "()"
    selector = Web3.keccak(text=sig)[:4].hex().lower()
    spaced = re.sub(r"(?<!^)(?=[A-Z])", " ", name).lower()  # NoPriceFeed -> "no price feed"
    return name, [selector, sig.lower(), spaced]


_TRANSIENT_ORACLE_MATCHERS = [_match_tokens(sig) for sig in _TRANSIENT_ORACLE_SIGS]
_ALREADY_SETTLED_MATCHERS = [_match_tokens(sig) for sig in _ALREADY_SETTLED_SIGS]


def transient_oracle_error_name(exc: BaseException) -> str | None:
    """Return the oracle-health error name if `exc` is a stale/missing/incomplete-feed revert.

    Returns None for any other error, so callers can distinguish an expected feed hiccup from a
    genuine fault. Matches against both the exception's `data` attribute and its string form,
    since web3 surfaces custom errors as either depending on ABI availability.
    """
    haystack = f"{getattr(exc, 'data', '')} {exc}".lower()
    for name, tokens in _TRANSIENT_ORACLE_MATCHERS:
        if any(token in haystack for token in tokens):
            return name
    return None


def already_settled_error_name(exc: BaseException) -> str | None:
    """Return the error name if `exc` means the loan was already repaid or liquidated.

    This is a normal race condition: the borrower repaid between the health-factor check and the
    liquidation tx. Returns None for any other error.
    """
    haystack = f"{getattr(exc, 'data', '')} {exc}".lower()
    for name, tokens in _ALREADY_SETTLED_MATCHERS:
        if any(token in haystack for token in tokens):
            return name
    return None


def _abi_search_dirs() -> list[Path]:
    """Directories to look for ABI JSON in, most specific first."""
    here = Path(__file__).resolve()
    dirs: list[Path] = []
    env_dir = os.environ.get("KEEPER_ABI_DIR")
    if env_dir:
        dirs.append(Path(env_dir))
    # Docker image: the extract-abi output is copied next to the app code (see Dockerfile).
    dirs.append(here.parent / "abi")
    # Local monorepo checkout: apps/keeper/chain.py -> repo root -> packages/abi.
    # In the Docker image chain.py sits at /app/chain.py, so parents[2] doesn't exist;
    # guard against that instead of letting IndexError kill startup.
    if len(here.parents) > 2:
        dirs.append(here.parents[2] / "packages" / "abi")
    return dirs


def _load_abi(name: str) -> list[dict[str, Any]]:
    """Load a contract ABI from the language-neutral JSON emitted by the contracts build.

    These files (packages/abi/<name>.json) are generated by
    packages/contracts/scripts/extract-abi.mjs, so the keeper's ABI always matches the
    compiled contract instead of drifting from a hand-maintained copy.
    """
    for base in _abi_search_dirs():
        path = base / f"{name}.json"
        if path.is_file():
            logger.debug("loaded %s ABI from %s", name, path)
            return json.loads(path.read_text())
    searched = ", ".join(str(base) for base in _abi_search_dirs())
    raise FileNotFoundError(
        f"{name}.json not found (searched: {searched}). "
        "Build the contracts first: `pnpm --filter @vouch/contracts build`."
    )


# getRepaymentDetails lives on the stateless VouchVaultLens companion contract (moved off the
# vault to stay under the 24 KB bytecode limit); everything else the keeper calls is on the vault.
_VAULT_ABI = _load_abi("VouchVault")
_LENS_ABI = _load_abi("VouchVaultLens")

_ERC20_ABI = [
    {
        "name": "approve",
        "type": "function",
        "inputs": [{"name": "spender", "type": "address"}, {"name": "amount", "type": "uint256"}],
        "outputs": [{"name": "", "type": "bool"}],
        "stateMutability": "nonpayable",
    },
    {
        "name": "allowance",
        "type": "function",
        "inputs": [{"name": "owner", "type": "address"}, {"name": "spender", "type": "address"}],
        "outputs": [{"name": "", "type": "uint256"}],
        "stateMutability": "view",
    },
    {
        "name": "balanceOf",
        "type": "function",
        "inputs": [{"name": "account", "type": "address"}],
        "outputs": [{"name": "", "type": "uint256"}],
        "stateMutability": "view",
    },
]


class VaultChain:
    def __init__(self, settings: Settings) -> None:
        self._w3 = Web3(Web3.HTTPProvider(settings.keeper_rpc_url))
        if not self._w3.is_connected():
            raise RuntimeError(f"Cannot connect to RPC at {settings.keeper_rpc_url}")
        self._account = self._w3.eth.account.from_key(settings.keeper_private_key)
        self._contract = self._w3.eth.contract(
            address=Web3.to_checksum_address(settings.keeper_contract_address),
            abi=_VAULT_ABI,
        )
        self._lens = self._w3.eth.contract(
            address=Web3.to_checksum_address(settings.keeper_lens_address),
            abi=_LENS_ABI,
        )

    def get_health_factor(self, loan_id: int) -> int:
        result: int = self._contract.functions.getHealthFactor(loan_id).call()
        return result

    def liquidate(self, loan_id: int) -> bool:
        requested_principal_token: str = self._contract.functions.loans(loan_id).call()[11]
        details = self._lens.functions.getRepaymentDetails(loan_id).call()
        remaining: int = details[5]

        if requested_principal_token != _ZERO_ADDRESS:
            return self._liquidate_erc20(loan_id, requested_principal_token, remaining)

        # ETH-principal: send msg.value; contract refunds any surplus. maxAmount is ignored.
        self._send_tx(
            self._contract.functions.liquidate(loan_id, 0, self._account.address),
            value=remaining,
        )
        return True

    def _liquidate_erc20(self, loan_id: int, token: str, max_amount: int) -> bool:
        token_address = Web3.to_checksum_address(token)
        erc20 = self._w3.eth.contract(address=token_address, abi=_ERC20_ABI)

        balance: int = erc20.functions.balanceOf(self._account.address).call()
        if balance < max_amount:
            logger.warning(
                "skipping loan %s: insufficient %s balance (have %s, need %s)",
                loan_id,
                token,
                balance,
                max_amount,
            )
            return False

        # Some tokens (e.g. USDT) revert when setting a non-zero allowance over an existing
        # non-zero one. Only reset if there's a stale allowance to clear.
        existing: int = erc20.functions.allowance(self._account.address, self._contract.address).call()
        if existing > 0:
            self._send_tx(erc20.functions.approve(self._contract.address, 0))
        self._send_tx(erc20.functions.approve(self._contract.address, max_amount))
        self._send_tx(
            self._contract.functions.liquidate(loan_id, max_amount, self._account.address)
        )
        return True

    def expire_loan(self, loan_id: int) -> None:
        self._send_tx(self._contract.functions.expireLoan(loan_id))

    def expire_lend_offer(self, offer_id: int) -> None:
        # On success this emits LendOfferExpired; the blockchain-listener catches it and flips
        # the lend_offers row to 'expired' in the DB, so the keeper only submits the tx.
        self._send_tx(self._contract.functions.expireLendOffer(offer_id))

    def _send_tx(self, fn: ContractFunction, value: int = 0) -> None:
        nonce = self._w3.eth.get_transaction_count(self._account.address, "pending")
        tx_params: dict[str, Any] = {"from": self._account.address, "nonce": nonce}
        if value:
            tx_params["value"] = value
        # estimate_gas simulates the call and raises with the actual revert reason if
        # it would fail, giving better diagnostics than a mined-but-reverted receipt.
        estimated = fn.estimate_gas(tx_params)
        tx_params["gas"] = int(estimated * 1.3)
        tx = fn.build_transaction(tx_params)
        signed = self._account.sign_transaction(tx)
        tx_hash = self._w3.eth.send_raw_transaction(signed.raw_transaction)
        receipt = self._w3.eth.wait_for_transaction_receipt(tx_hash, timeout=120)
        if receipt["status"] != 1:
            raise RuntimeError(f"Transaction reverted: {tx_hash.hex()}")
        logger.info("tx %s mined in block %s", tx_hash.hex(), receipt["blockNumber"])
