from __future__ import annotations

import json
import logging
import os
from pathlib import Path
from typing import Any

from web3 import Web3
from web3.contract.contract import ContractFunction

from config import Settings

logger = logging.getLogger("vouch.keeper.chain")

_ZERO_ADDRESS = "0x0000000000000000000000000000000000000000"


def _abi_search_dirs() -> list[Path]:
    """Directories to look for ABI JSON in, most specific first."""
    here = Path(__file__).resolve()
    dirs: list[Path] = []
    env_dir = os.environ.get("KEEPER_ABI_DIR")
    if env_dir:
        dirs.append(Path(env_dir))
    # Docker image: the extract-abi output is copied next to the app code (see Dockerfile).
    dirs.append(here.parent / "abi")
    # Local monorepo checkout: apps/keeper/chain.py -> repo root -> packages/abi.
    dirs.append(here.parents[2] / "packages" / "abi")
    return dirs


def _load_abi(name: str) -> list[dict[str, Any]]:
    """Load a contract ABI from the language-neutral JSON emitted by the contracts build.

    These files (packages/abi/<name>.json) are generated by
    packages/contracts/scripts/extract-abi.mjs, so the keeper's ABI always matches the
    compiled contract instead of drifting from a hand-maintained copy.
    """
    for base in _abi_search_dirs():
        path = base / f"{name}.json"
        if path.is_file():
            logger.debug("loaded %s ABI from %s", name, path)
            return json.loads(path.read_text())
    searched = ", ".join(str(base) for base in _abi_search_dirs())
    raise FileNotFoundError(
        f"{name}.json not found (searched: {searched}). "
        "Build the contracts first: `pnpm --filter @vouch/contracts build`."
    )


# getRepaymentDetails lives on the stateless VouchVaultLens companion contract (moved off the
# vault to stay under the 24 KB bytecode limit); everything else the keeper calls is on the vault.
_VAULT_ABI = _load_abi("VouchVault")
_LENS_ABI = _load_abi("VouchVaultLens")


class VaultChain:
    def __init__(self, settings: Settings) -> None:
        self._w3 = Web3(Web3.HTTPProvider(settings.keeper_rpc_url))
        if not self._w3.is_connected():
            raise RuntimeError(f"Cannot connect to RPC at {settings.keeper_rpc_url}")
        self._account = self._w3.eth.account.from_key(settings.keeper_private_key)
        self._contract = self._w3.eth.contract(
            address=Web3.to_checksum_address(settings.keeper_contract_address),
            abi=_VAULT_ABI,
        )
        self._lens = self._w3.eth.contract(
            address=Web3.to_checksum_address(settings.keeper_lens_address),
            abi=_LENS_ABI,
        )

    def get_health_factor(self, loan_id: int) -> int:
        result: int = self._contract.functions.getHealthFactor(loan_id).call()
        return result

    def liquidate(self, loan_id: int) -> None:
        # The keeper funds liquidations with ETH (msg.value). For ERC20-principal loans the
        # contract's liquidate() rejects msg.value and instead pulls `maxAmount` via an ERC20
        # allowance, which requires the keeper to hold and approve that token — unsupported here.
        # Skip them so we don't repeatedly broadcast guaranteed-to-revert txs and burn gas.
        requested_principal_token: str = self._contract.functions.loans(loan_id).call()[11]
        if requested_principal_token != _ZERO_ADDRESS:
            logger.info(
                "skipping loan %s: ERC20-principal (%s) liquidation not supported by keeper",
                loan_id,
                requested_principal_token,
            )
            return

        # Fetch the outstanding debt (from the lens) to send as msg.value; contract refunds
        # any surplus. maxAmount is ignored on the ETH path, so pass 0.
        details = self._lens.functions.getRepaymentDetails(loan_id).call()
        remaining: int = details[5]
        self._send_tx(
            self._contract.functions.liquidate(loan_id, 0, self._account.address),
            value=remaining,
        )

    def expire_loan(self, loan_id: int) -> None:
        self._send_tx(self._contract.functions.expireLoan(loan_id))

    def expire_lend_offer(self, offer_id: int) -> None:
        # On success this emits LendOfferExpired; the blockchain-listener catches it and flips
        # the lend_offers row to 'expired' in the DB, so the keeper only submits the tx.
        self._send_tx(self._contract.functions.expireLendOffer(offer_id))

    def _send_tx(self, fn: ContractFunction, value: int = 0) -> None:
        nonce = self._w3.eth.get_transaction_count(self._account.address)
        tx_params: dict[str, Any] = {
            "from": self._account.address,
            "nonce": nonce,
            "gas": 200_000,
        }
        if value:
            tx_params["value"] = value
        tx = fn.build_transaction(tx_params)
        signed = self._account.sign_transaction(tx)
        tx_hash = self._w3.eth.send_raw_transaction(signed.raw_transaction)
        receipt = self._w3.eth.wait_for_transaction_receipt(tx_hash, timeout=120)
        if receipt["status"] != 1:
            raise RuntimeError(f"Transaction reverted: {tx_hash.hex()}")
        logger.info("tx %s mined in block %s", tx_hash.hex(), receipt["blockNumber"])
